### ISSUE TITLE
add sugar cane uu-matter recipe

### ISSUE THREAD

**Issue by NarigudoBR** [CrankySupertoonArchive/Pyramid-Challenge-Reborn#39]
there's no way of getting sugar cane in the modpack

**Comment by furtabs** [comment]
Just curious what do you need sugar cane for?

**Comment by furtabs** [comment]
in the original map i think you had to IC2 Crop breed, but that i think was removed so yeah smart call

**Comment by NarigudoBR** [comment]
In the original map you could do this, so, why not? also i will make a issue about getting apatite(i want my farms running!)

**Comment by furtabs** [comment]
In the original map there was no way to make apatite. The intent was to make compost

**Comment by NarigudoBR** [comment]
yeah but the farms cant work without apatite

**Comment by NarigudoBR** [comment]
> yeah but the farms cant work without apatite

in this version(yeah i tried with compost but nope :(
