### ISSUE TITLE
Playing on Normal map - Companion Cube not recognized, or fails to update quest.

### ISSUE THREAD

**Issue by Michael-McKinley** [CrankySupertoonArchive/Pyramid-Challenge-Reborn#45]
version 1.6.0
downloaded from Curse two days ago.

Found Reddit reply to same issue stating to run /gamerule questfile normal and restart map.

Unclear as to what restart map means.
Tried: 
1) command (response mode updated to normal) - save - exit - load - create and supply new Companion Cube - still fails to acknowledge Companion Cube.
2) delete current game - create new beast (normal) - launch - run command - save - exit - launch - progress to Companion Cube - supply Companion Cube by dropping on item importer - quest still fails to update.

**Comment by furtabs** [comment]
its **/gamerule questfile norm** and i really do have to fix this.

Literally the quest will reconize after this no map restart needed

**Comment by furtabs** [comment]
well i mean reload the pack but dont lose progress

**Comment by furtabs** [comment]
EIther that or restart on 1.7.0
