### ISSUE TITLE
Can't download from Twitch

### ISSUE THREAD

**Issue by Drawde2** [CrankySupertoonArchive/Pyramid-Challenge-Reborn#67]
Every time I try to download this modpack from Twitch it fails and I get an error message.

Could not read C\:Users\***\4742CD0808154AAE834D0430E4BED0FD\330.zip as a zip file

This has happened on two different computers.  Version from 4/3/2020 for 1.12.2.

**Comment by furtabs** [comment]
Hmm, I have a guess on what causes it but it still shouldn’t be. Care trying another launcher such as MultiMC. Think it might be that your directory path is over 20 characters

**Comment by Drawde2** [comment]
Tried MultiMC, but can't figure out how to get the modpack on it.  Tried downloading the pack from Curseforge, and I always end up with a pack with no mods.  I have no problems with other packs on Twitch, just this one.  And as I said above, it did this on two computers.
