### ISSUE TITLE
Quests missing?

### ISSUE THREAD

**Issue by Vercalos** [CrankySupertoonArchive/Pyramid-Challenge-Reborn#68]
Just did a fresh install of 2.1.0 but all the quests appear be missing entirely. Also, had no starting inventory and started on a single dirt block on a void map, making the pack completely unplayable without admin codes.

**Comment by furtabs** [comment]
This is not a bug. On the main menu of the modpack there should be a download maps button that fetches the maps from our new CDN Server for less file size and less modpack updates. The quests do not appear in a normal world.

**Comment by furtabs** [comment]
I really do have to make it more clear TBH

**Comment by Vercalos** [comment]
Maybe a default quest on the default map that would instruct you to go back to the main menu and download the relevant map?

Also, I feel like an idiot for asking this, but how does this map even work?  I downloaded it, I got to the pyramid, even made a transmutation table, but I'm honestly not sure how to progress or complete any of the quests.

**Comment by furtabs** [comment]
Sorry for the late responce. Are you stuck on Iron? My one clue is zombie pigman drop gold
