### ISSUE TITLE
Bug ender chest quest

### ISSUE THREAD

**Issue by sync777** [CrankySupertoonArchive/Pyramid-Challenge-Reborn#69]
playing on Normal map
when completing the quest ender chest
it does not count, and the chest itself goes into the void transport pipe
tell me what to do?
[http://prntscr.com/1139m4g](url)
[http://prntscr.com/1139nwm](url)

**Comment by furtabs** [comment]
Let me take a quick peek. Most likely just needs a pack update after i fix something my side.

**Comment by sync777** [comment]
it is my save game
https://cloud.mail.ru/public/XvFp/NUZ7KyfTy

**Comment by furtabs** [comment]
Sorry for the late response, your save seems to of been fine. By any chance could you have forgotten to claim the reward.
